### ISSUE TITLE
Docker group id change in 20211103 

### ISSUE THREAD

**Issue by sushant-pradhan** [aws/amazon-ecs-ami#16]
### Summary
Change in docker gid

### Description
Between ECS Optimized Amz Linux2 AMI versions 20211013 and 20211103 the docker group id has changed from 996 to 994

```bash
# 20211103 
$ cat /etc/group | grep docker
docker:x:994:ec2-user

# 20211013 
$ cat /etc/group | grep docker
docker:x:996:ec2-user
```

This is causing errors in some scenarios where the docker daemon is to be shared with another user and this unexpected gid change is breaking it.

### Expected Behavior

The gid for docker group should remain same: 996

**Comment by jhmartin** [comment]
Can you expand on why you want to share the docker daemon user with another user?

**Comment by sushant-pradhan** [comment]
> Can you expand on why you want to share the docker daemon user with another user?

I am running a CI server on the instance and want to run a docker build command. So by adding the CI user to docker group is what I did in past but is broken now

**Comment by jhmartin** [comment]
What command are you using to do that? I'd expect you could either add it by name, or look up the id beforehand and use that.

**Comment by sushant-pradhan** [comment]
> What command are you using to do that? I'd expect you could either add it by name, or look up the id beforehand and use that instead of depending on a specific value.

Well.. the CI process is running as a container. So during build of the container image, I need to add the container's user to the host's docker group. So it can't be looked up inside the container.

BTW.. is it acknowledged that this change happened? Any changelog/release notes which cover this change?

**Comment by sparrc** [comment]
Hi Sushant, there is no changelog acknowledgement of this as there didnt exist an ECS AMI changelog before 20211115. Before 20211115 and this repo existing, we were using a different internal process for building the AMI.

But I would highly recommend you don't do this operation based on the group ID. Group ID for most packages (including docker) is not hard-coded into the package, it's randomly assigned based on what group IDs that system has available at the time of installation. So any time that AL2 adds a package to the underlying OS, or we add or delete a package from the ECS AMI, or we change the order of package installation, then you might see a group ID change.

You should be able to fix your scripts to reference group `docker` instead of `996`:

```
sudo usermod -a -G docker myContainerUser
```

**Comment by sushant-pradhan** [comment]
@sparrc  in my last 2 yrs of using amz ecs optimized base image, the group id has remained constant as 996. You can verify yourself. So if there is a change which wasnt in earlier, shouldn't it be analyzed instead if taking the easy path of closing the ticket. Can you explain how can I read the host group's id at runtime?

**Comment by sushant-pradhan** [comment]
Or @sparrc  can it be added in the release notes as a breaking change that from 20211115  the gid is changed as 994 and is going to be 994 going forward? Lack of release notes is a big concern not really the change

**Comment by jhmartin** [comment]
How is the CI process launched? It could run the following and pass that in as a variable:
`$ getent group docker`
`docker:x:994:`

**Comment by sushant-pradhan** [comment]
@jhmartin Its not always as simple... I use this plugin: https://github.com/jenkinsci/amazon-ecs-plugin: this launches individual jobs as tasks in ecs.

**Comment by jhmartin** [comment]
That does complicate things a bit.  Perhaps switching to the network interface for the docker daemon?
