### ISSUE TITLE
Docker version vulnerable to cve-2023-29406

### ISSUE THREAD

**Issue by swehner** [aws/amazon-ecs-ami#225]
### Summary

The current docker version 20.10.15 is vulnerable to a few issues, like:
https://nvd.nist.gov/vuln/detail/cve-2023-29406
https://nvd.nist.gov/vuln/detail/cve-2023-39325

And same for containerd: 1.7.2 is also affected by a few issues
https://nvd.nist.gov/vuln/detail/cve-2023-47108

Is there any plan on updating docker and containerd versions for this image?

**Comment by majd** [comment]
This was addressed in #231.

**Comment by sparrc** [comment]
Thanks for the ticket, we have bumped to docker 25.0.3 for AL2023

Also keep in mind that the docker versions in NIST CVE notices don't always 100% map to the docker version in Amazon Linux. If you look at CVE 2023-39325 in ALAS, for example, and then click through to the Amazon Linux 2 advisories, you can see that this CVE is fixed in 20.10.15 in Amazon Linux: https://alas.aws.amazon.com/cve/html/CVE-2023-39325.html

As soon as Amazon Linux 2 releases docker 25.0.3 we will be bumping our AL2 AMIs.

**Comment by charlesbjohnson** [comment]
> As soon as Amazon Linux 2 releases docker 25.0.3 we will be bumping our AL2 AMIs.

I think Docker 25.0.3 is now in the AL2 repos, could we get an AMI bump? 🙏

<img width="993" alt="Screenshot 2024-07-08 at 4 19 06 PM" src="https://github.com/aws/amazon-ecs-ami/assets/4823640/9e0c9a72-4a29-4609-bc00-0c84775b0fb6">

<img width="390" alt="Screenshot 2024-07-08 at 4 19 49 PM" src="https://github.com/aws/amazon-ecs-ami/assets/4823640/93bc6152-2c34-450c-91a0-c3260ad02759">

**Comment by charlesbjohnson** [comment]
> I think Docker 25.0.3 is now in the AL2 repos, could we get an AMI bump? 🙏

Thank you for the quick response! https://github.com/aws/amazon-ecs-ami/pull/269

I think this issue can be closed.
