### ISSUE TITLE
Question: Pre-cached containers

### ISSUE THREAD

**Issue by oscarnevarezleal** [aws/amazon-ecs-ami#98]
### Summary
In the original [post](https://aws.amazon.com/blogs/containers/creating-custom-amazon-machine-images-with-the-ecs-optimized-ami-build-recipes/), it is explained one of the benefits of custom AMIs is pre-cached containers. 

### Description

I'd like to pull some containers before the AMI finish its build process. 
Two questions:

- If I achieve this are those docker layers preserved in the generated AMI?
- What's the best way to do this? I thought it might be easy to do as adding the commands in a file or creating a bash script but I couldn’t find any reference to this approach except for RMPS in additional-packages folder.

**Comment by Realmonia** [comment]
Hi @oscarnevarezleal ,

1. Yeah, everything you did in the AMI creation process should be kept unless removed specifically in https://github.com/aws/amazon-ecs-ami/blob/main/scripts/cleanup.sh
2. Since what you would like to do is to pull some container, what you mentioned (adding the commands in a file or creating a bash script) should work. Just need to make sure it is done after the container runtime is installed and enabled. You can see the order of script execution in files like https://github.com/aws/amazon-ecs-ami/blob/main/al2.pkr.hcl. Here, I think you can add the file/shell provisioner [here](https://github.com/aws/amazon-ecs-ami/blob/main/al2.pkr.hcl#L183). For how to use file/shell provisioner, you can find documentation [here](https://developer.hashicorp.com/packer/docs/provisioners).

Please feel free to reopen if you need any more help!
